sudo: false
language: ruby
cache: bundler
rvm:
  - 2.5.0
before_install: gem install bundler -v 1.16.4

jobs:
  include:
    - name: "Building carthframie"
      stage: compile
      script: bundle exec rake build
    - name: "Testing carthframie"
      stage: test
      script: bundle exec rspec spec
